In [1]:
import torch

In [3]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))
#     print("Добавим 10 :\n%s\n" % (tensor + 10))
#     print("Среднее по строчке :\n%s\n" % (tensor.mean(axis=-1)))
#     print("Среднее по столбцу :\n%s\n" % (tensor.mean(axis=0)))

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
x = torch.randn(3, 4, 5)
print_tens_info(x)

X :
tensor([[[-1.5389e-01, -5.5880e-01,  4.2030e-01, -1.1919e+00, -1.8549e+00],
         [-4.7502e-01,  5.5980e-01,  1.3674e+00, -1.0457e-01,  3.9537e-01],
         [ 9.5713e-01, -4.5634e-02, -7.6788e-04,  9.5532e-01, -5.3944e-01],
         [-9.1943e-01,  1.4550e+00,  5.1817e-01, -1.4216e+00,  6.9016e-01]],

        [[ 3.0965e-01, -1.5968e-01,  3.7716e-01, -4.7984e-01, -1.1975e+00],
         [ 4.1007e-01,  9.3218e-01, -7.2162e-01,  1.1319e+00, -6.9453e-04],
         [ 3.1774e-01, -4.1312e-01,  8.3485e-01,  5.0918e-01,  1.6145e+00],
         [-1.2735e+00, -2.3694e-01, -1.2246e+00,  1.0299e+00, -4.0779e-01]],

        [[ 2.8000e-01,  8.0084e-01,  7.8458e-01, -1.7037e+00, -1.1369e+00],
         [-1.1261e+00,  6.1284e-01, -4.8419e-02,  3.6846e-01, -2.5564e-01],
         [-1.8103e+00, -9.5504e-01, -7.4193e-03, -6.5713e-01, -1.0972e+00],
         [ 5.5592e-01,  1.5934e+00,  1.0462e-01,  1.1603e+00, -6.7349e-01]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.F

In [ ]:
# Выведите его форму (shape)

In [5]:
x.shape

torch.Size([3, 4, 5])

In [ ]:
# Приведите его к форме 6 X 10

In [27]:
x_6_10 = torch.reshape(x, (6, 10))

In [28]:
x_6_10

tensor([[-1.5389e-01, -5.5880e-01,  4.2030e-01, -1.1919e+00, -1.8549e+00,
         -4.7502e-01,  5.5980e-01,  1.3674e+00, -1.0457e-01,  3.9537e-01],
        [ 9.5713e-01, -4.5634e-02, -7.6788e-04,  9.5532e-01, -5.3944e-01,
         -9.1943e-01,  1.4550e+00,  5.1817e-01, -1.4216e+00,  6.9016e-01],
        [ 3.0965e-01, -1.5968e-01,  3.7716e-01, -4.7984e-01, -1.1975e+00,
          4.1007e-01,  9.3218e-01, -7.2162e-01,  1.1319e+00, -6.9453e-04],
        [ 3.1774e-01, -4.1312e-01,  8.3485e-01,  5.0918e-01,  1.6145e+00,
         -1.2735e+00, -2.3694e-01, -1.2246e+00,  1.0299e+00, -4.0779e-01],
        [ 2.8000e-01,  8.0084e-01,  7.8458e-01, -1.7037e+00, -1.1369e+00,
         -1.1261e+00,  6.1284e-01, -4.8419e-02,  3.6846e-01, -2.5564e-01],
        [-1.8103e+00, -9.5504e-01, -7.4193e-03, -6.5713e-01, -1.0972e+00,
          5.5592e-01,  1.5934e+00,  1.0462e-01,  1.1603e+00, -6.7349e-01]])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [8]:
y = torch.LongTensor([1, 4, 2, 2, 1])
torch.mul(x, y)

tensor([[[-1.5389e-01, -2.2352e+00,  8.4061e-01, -2.3838e+00, -1.8549e+00],
         [-4.7502e-01,  2.2392e+00,  2.7349e+00, -2.0914e-01,  3.9537e-01],
         [ 9.5713e-01, -1.8253e-01, -1.5358e-03,  1.9106e+00, -5.3944e-01],
         [-9.1943e-01,  5.8199e+00,  1.0363e+00, -2.8433e+00,  6.9016e-01]],

        [[ 3.0965e-01, -6.3871e-01,  7.5432e-01, -9.5969e-01, -1.1975e+00],
         [ 4.1007e-01,  3.7287e+00, -1.4432e+00,  2.2638e+00, -6.9453e-04],
         [ 3.1774e-01, -1.6525e+00,  1.6697e+00,  1.0184e+00,  1.6145e+00],
         [-1.2735e+00, -9.4776e-01, -2.4493e+00,  2.0598e+00, -4.0779e-01]],

        [[ 2.8000e-01,  3.2033e+00,  1.5692e+00, -3.4073e+00, -1.1369e+00],
         [-1.1261e+00,  2.4514e+00, -9.6837e-02,  7.3691e-01, -2.5564e-01],
         [-1.8103e+00, -3.8202e+00, -1.4839e-02, -1.3143e+00, -1.0972e+00],
         [ 5.5592e-01,  6.3734e+00,  2.0924e-01,  2.3207e+00, -6.7349e-01]]])

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [29]:
x_10_6 = torch.transpose(x_6_10, 0, 1)

In [31]:
x_6_6 = torch.matmul(x_6_10, x_10_6)
x_6_6.shape, x_6_6

(torch.Size([6, 6]),
 tensor([[ 7.9499,  2.1212,  2.2148, -4.5399,  4.6508,  4.0108],
         [ 2.1212,  7.8500, -0.5133, -1.6161,  0.4183, -1.9780],
         [ 2.2148, -0.5133,  4.7668, -0.3918,  2.9954,  4.1699],
         [-4.5399, -1.6161, -0.3918,  8.2392, -0.4580, -2.0368],
         [ 4.6508,  0.4183,  2.9954, -0.4580,  7.3775,  2.0345],
         [ 4.0108, -1.9780,  4.1699, -2.0368,  2.0345, 10.4835]]))

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [32]:
from torch.autograd import Variable

In [49]:
x = Variable(torch.FloatTensor([1.]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2.]), requires_grad = True)

In [50]:
y = x**3 + z - 75*t

In [51]:
y.backward([x, z, t])

In [52]:
x.grad + z.grad + t.grad

tensor([-71.])

In [53]:
# Создайте единичный тензор размера 5x6
q_5_6 = torch.ones(5, 6)

In [ ]:
# Переведите его в формат numpy

In [56]:
np_5_6 = q_5_6.numpy()
np_5_6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [93]:
from torch import nn
from torch import optim

In [207]:
x = Variable(torch.randn(1), requires_grad = True)
y = Variable(torch.randn(1), requires_grad = False)
w1 =  Variable(torch.randn(1), requires_grad = True)
w1, x, y

(tensor([-0.6836], requires_grad=True),
 tensor([1.7620], requires_grad=True),
 tensor([1.0269]))

In [208]:
def func(x):
  return x**w1 - 2 * x**2 + 5

In [209]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [210]:
optimizer.zero_grad()
pred = func(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  2.4254884719848633


In [211]:
loss.backward()

In [212]:
optimizer.step()

In [213]:
w1

tensor([-0.6824], requires_grad=True)